apiVersion: v1
kind: ServiceAccount
metadata:
  name: java-user

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: java-server-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - create
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  - workflowtemplates/finalizers
  - clusterworkflowtemplates
  - clusterworkflowtemplates/finalizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - argoproj.io
  resources:
  - cronworkflows
  - cronworkflows/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: java-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: java-server-role
subjects:
- kind: ServiceAccount
  name: java-user
  namespace: java

---

apiVersion: v1
kind: Service
metadata:
  name: java-server
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 8086
    targetPort: 8086
  selector:
    app: java-server


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-server
spec:
  selector:
    matchLabels:
      app: java-server
  template:
    metadata:
      labels:
        app: java-server
    spec:
      containers:
        - name: java-server
          image: tanvishiitg/javaserver:v2
          ports:
            - name: web
              containerPort: 8086
       serviceAccountName: java-user
         
